[package]
name = "gcalendar_time_track"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-calendar = "0.7.0"
tokio = {version = "1.40.0", features = ["full", "rt-multi-thread"]}
